---
- name: Configure Azure VM with essential tools
  hosts: azure_vms
  become: yes
  gather_facts: yes
  
  vars:
    packages:
      - git
      - curl
      - wget
      - vim
      - htop
      - tree
      - unzip
      - python3-pip
      - nginx
      - nodejs
      - npm
      
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Install essential packages
      apt:
        name: "{{ packages }}"
        state: present
        
    - name: Create a custom user directory
      file:
        path: /home/azureuser/apps
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'
        
    - name: Start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
        
    - name: Create a simple index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>BCDV Lab4 - Ansible Demo</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .container { max-width: 800px; margin: 0 auto; }
                  .info { background: #f4f4f4; padding: 20px; border-radius: 5px; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 BCDV Lab4 - Ansible Configuration</h1>
                  <div class="info">
                      <h2>VM Information</h2>
                      <p><strong>Hostname:</strong> {{ ansible_hostname }}</p>
                      <p><strong>OS:</strong> {{ ansible_distribution }} {{ ansible_distribution_version }}</p>
                      <p><strong>IP Address:</strong> {{ ansible_default_ipv4.address }}</p>
                      <p><strong>Configured by:</strong> Ansible Playbook</p>
                      <p><strong>Date:</strong> {{ ansible_date_time.date }}</p>
                  </div>
                  <p>This VM was automatically configured using Ansible! 🎉</p>
              </div>
          </body>
          </html>
        dest: /var/www/html/index.html
        backup: yes
        
    - name: Display deployment summary
      debug:
        msg: |
          🎉 VM Configuration Complete!
          
          VM Details:
          - Hostname: {{ ansible_hostname }}
          - Public IP: {{ ansible_host }}
          - OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          - Web Server: http://{{ ansible_host }}
          
          Installed Packages: {{ packages | join(', ') }}
