---
- name: Test Ansible Connection to Azure VM
  hosts: azure_vms
  gather_facts: yes
  
  tasks:
    - name: Test connection with ping
      ping:
      
    - name: Display system information
      debug:
        msg: |
          Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Architecture: {{ ansible_architecture }}
          IP Address: {{ ansible_default_ipv4.address }}
          Memory: {{ ansible_memtotal_mb }}MB
          CPU Cores: {{ ansible_processor_vcpus }}
          
    - name: Check disk usage
      shell: df -h /
      register: disk_usage
      
    - name: Display disk usage
      debug:
        msg: "Root filesystem usage: {{ disk_usage.stdout_lines }}"
        
    - name: Check system uptime
      shell: uptime
      register: system_uptime
      
    - name: Display uptime
      debug:
        msg: "System uptime: {{ system_uptime.stdout }}"
